added versioning

diff --git a/.github/workflows/docker-build-and-push.yml b/.github/workflows/docker-build-and-push.yml
--- a/.github/workflows/docker-build-and-push.yml
+++ b/.github/workflows/docker-build-and-push.yml
@@ -2,11 +2,15 @@ name: Build Docker Image
 
 on:
   push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+    tags:
+      - 'v*'
+      - 'latest'
+  workflow_dispatch:
+    inputs:
+      tag:
+        description: 'Tag to build (e.g., v1.2.3 or latest)'
+        required: true
+        default: 'latest'
 
 # Load from versions.txt later on
 # Or do this in the docker file
@@ -28,6 +32,12 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+
+      - name: Check out the repository
+        uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.tag || github.ref }}
+
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v3
         with:
@@ -42,14 +52,40 @@ jobs:
           username: ${{ secrets.DOCKER_HUB_USERNAME }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
+      - name: Set build environment variables
+        id: set-env
+        run: |
+          TAG_NAME=${{ github.event.inputs.tag || github.ref }}
+          if [[ "$TAG_NAME" == "refs/tags/latest" || "$TAG_NAME" == "latest" ]]; then
+            VERSION_FILE="versions.txt"
+            IMAGE_TAG="latest"
+          else
+            VERSION_NUMBER=$(basename "$TAG_NAME")
+            VERSION_FILE="freeze/versions_${VERSION_NUMBER}.txt"
+            IMAGE_TAG="$VERSION_NUMBER"
+          fi          
+          if [ -f "$VERSION_FILE" ]; then
+            echo "Found settings file for version $TAG_NAME"
+            source $VERSION_FILE
+            echo "MICROMAMBA_VERSION=${MICROMAMBA_VERSION}" >> $GITHUB_ENV
+            echo "PANDOC_VERSION=${PANDOC_VERSION}" >> $GITHUB_ENV
+            echo "PANDOC_CLI_VERSION=${PANDOC_CLI_VERSION}" >> $GITHUB_ENV
+            echo "PANDOC_CROSSREF_VERSION=${PANDOC_CROSSREF_VERSION}" >> $GITHUB_ENV
+            echo "LUA_VERSION=${LUA_VERSION}" >> $GITHUB_ENV
+            echo "PANDOC_PLOT_VERSION=${PANDOC_PLOT_VERSION}" >> $GITHUB_ENV
+          else
+            echo "Settings file for version $TAG_NAME not found"
+            exit 1
+          fi
+
       - name: Build and export to Docker
         uses: docker/build-push-action@v6
         with:
           load: true
-          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:test
-          # platforms: linux/amd64
-          #, linux/arm64
-          # platforms: linux/arm64, 
+          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/{{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
+          platforms: linux/amd64
+          # test just on amd64 for the moment
+          # ,linux/arm64
           build-args: |
             MICROMAMBA_VERSION=${{ env.MICROMAMBA_VERSION }}
             ENVIRONMENT_FILE=${{ env.ENVIRONMENT_FILE }}
@@ -58,15 +94,15 @@ jobs:
             PANDOC_CROSSREF_VERSION=${{ env.PANDOC_CROSSREF_VERSION }}
             LUA_VERSION=${{ env.LUA_VERSION }}
             PANDOC_PLOT_VERSION=${{ env.PANDOC_PLOT_VERSION }}
+
       - name: Test
         run: |
           docker run --rm ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:test /bin/bash ./run_tests.sh
+
       - name: Build and push
         uses: docker/build-push-action@v6
         with:
           platforms: linux/amd64, linux/arm64
-          # , linux/arm64
-          # platforms: linux/arm64, linux/amd64
           build-args: |
             MICROMAMBA_VERSION=${{ env.MICROMAMBA_VERSION }}
             ENVIRONMENT_FILE=${{ env.ENVIRONMENT_FILE }}
@@ -76,6 +112,4 @@ jobs:
             LUA_VERSION=${{ env.LUA_VERSION }}
             PANDOC_PLOT_VERSION=${{ env.PANDOC_PLOT_VERSION }}          
           push: true
-          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:final
-
-
+          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/{{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
